[project]
name = "unit-converter"
version = "0.1.0"
description = "Swift Unit Converter Web App"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["streamlit>=1.43.2"]
packages = [{include = "unit_converter"}] 